schema_version = "1.0.0"

id = "nitrog3d"
version = "1.1.0"
name = "nitrog3d"
tagline = "Extension to work with Nintendo DS NITRO 3D File Formats"
maintainer = "Fexty"
type = "add-on"

website = "https://github.com/Fexty12573/nitrog3d"
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["MIT"]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    "/.git/",
    "/.gitignore",
    "/.gitattributes",
    "/.venv/",
    "/.vscode/",
    "/.pytest_cache/",
    "/tools/",
    "/tests/",
    "/data/",
    "/pytest.ini",
    "*.zip",
]
